baseURL: "https://mechinterpworkshop.com/"
languageCode: "en-us"
title: "Mechanistic Interpretability Workshop at ICML 2026"
theme: "ananke"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  description: "The Mechanistic Interpretability Workshop at ICML 2026. How can we use the internals of neural networks to understand a model better?"
  show_reading_time: false

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Schedule"
      url: "/schedule/"
      weight: 2
    - name: "Call for Papers"
      url: "/cfp/"
      weight: 3
    - identifier: "previous"
      name: "Previous Workshops"
      weight: 10
    - name: "NeurIPS 2025"
      parent: "previous"
      url: "/neurips2025/"
      weight: 1
    - name: "ICML 2024"
      parent: "previous"
      url: "https://icml2024mi.pages.dev/"
      weight: 2
