name: Sync Google Docs

on:
  schedule:
    - cron: "0 * * * *"        # hourly
  workflow_dispatch:           # manual trigger
  push:
    branches: [main]          # also run on push to main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib pyyaml

      - name: Pull Google Docs → Markdown
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          GDOCS_FOLDER_ID: ${{ secrets.GDOCS_FOLDER_ID }}
        run: |
          python scripts/sync_gdocs.py

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "sync: Google Docs → Markdown [skip ci]"
            git push
          fi
